// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyiujjjndaazkulbubpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5aXVqampuZGFhemt1bGJ1YnByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzk0NTcsImV4cCI6MjA3Mzk1NTQ1N30.f2j7c-nNh9EOyp7NL46inGMVIyju7HncftTjGFymuh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});